apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: onlineeventbookingali
data:
  MONGO_INITDB_DATABASE: events_db
  MONGO_DB_HOST: mongodb-service
  MONGO_DB_PORT: "27017"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672"
  EVENT_SERVICE_URL: "http://localhost:30002"