apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: onlineeventbookingali
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ291c2Vy   # base64 of 'mongouser'
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=   # base64 of 'password'